name: task_management
description: "This app is personal task management system. You can create, edit and delete by signup. And you can pritiorize your tasks."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: 0.18.0
  go_router: 13.2.3
  flutter_riverpod: 2.5.1
  riverpod_annotation: 2.3.5
  rxdart: 0.27.7
  uuid: ^4.4.0

  equatable: ^2.0.5
  cupertino_icons: ^1.0.6
  flutter_slidable: ^3.1.0
  flutterfire_cli: ^1.0.0
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  firebase_database: ^10.5.1
  flutter_local_notifications: ^17.0.1
  flutter_timezone: ^1.0.8
  hive: ^2.2.3
  path_provider: ^2.1.3
  hive_generator: ^2.0.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.9
  riverpod_generator: 2.4.0

  
  flutter_lints: ^3.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
