// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRm5NG53L5Ed7L6taeVFOEoNyhdFKJjY8',
    appId: '1:588989544561:web:870dd5bd94f0c2b76803d0',
    messagingSenderId: '588989544561',
    projectId: 'task-9f904',
    authDomain: 'task-9f904.firebaseapp.com',
    databaseURL: 'https://task-9f904-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-9f904.appspot.com',
    measurementId: 'G-C63XSGCCPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC40NyTChKOb-tQyDaYGV7MmD-c3lDjA6o',
    appId: '1:588989544561:android:73dd7aa088df77a66803d0',
    messagingSenderId: '588989544561',
    projectId: 'task-9f904',
    databaseURL: 'https://task-9f904-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-9f904.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6j5JcHSHj5iN8tsSz80fPrN0BIprNVts',
    appId: '1:588989544561:ios:83cdf8e1276a45ee6803d0',
    messagingSenderId: '588989544561',
    projectId: 'task-9f904',
    databaseURL: 'https://task-9f904-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-9f904.appspot.com',
    iosBundleId: 'dev.mml.task',
  );
}
